"use client";

import { useEffect, useMemo, useRef, useState } from "react";
export type TrafficPoint={month:string;label:string;visits:number;visitors:number};

export function TrafficChart({data}:{data:TrafficPoint[]}){
  const canvasRef=useRef<HTMLCanvasElement>(null),[selected,setSelected]=useState(data.length-1);
  const peak=Math.max(1,...data.map(point=>point.visits)),current=data.at(-1)?.visits??0,previous=data.at(-2)?.visits??0;
  const growth=previous>0?Math.round(((current-previous)/previous)*100):current>0?100:0,total=data.reduce((sum,point)=>sum+point.visits,0),selectedPoint=data[Math.max(0,selected)],chartKey=useMemo(()=>JSON.stringify(data),[data]);
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const draw=()=>{const bounds=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.round(bounds.width*ratio));canvas.height=Math.max(1,Math.round(bounds.height*ratio));const context=canvas.getContext("2d");if(!context)return;context.scale(ratio,ratio);const width=bounds.width,height=bounds.height,pad={left:48,right:18,top:20,bottom:35},innerW=width-pad.left-pad.right,innerH=height-pad.top-pad.bottom;context.clearRect(0,0,width,height);context.font="11px DM Sans, Arial";context.lineWidth=1;for(let line=0;line<=4;line++){const y=pad.top+(innerH/4)*line,value=Math.round(peak*(1-line/4));context.strokeStyle="#e7ebf1";context.beginPath();context.moveTo(pad.left,y);context.lineTo(width-pad.right,y);context.stroke();context.fillStyle="#929aa7";context.textAlign="right";context.fillText(String(value),pad.left-10,y+4)}const step=data.length>1?innerW/(data.length-1):innerW,points=data.map((point,index)=>({x:pad.left+(data.length>1?index*step:innerW/2),y:pad.top+innerH-(point.visits/peak)*innerH}));if(points.length){const gradient=context.createLinearGradient(0,pad.top,0,pad.top+innerH);gradient.addColorStop(0,"rgba(42,105,224,.24)");gradient.addColorStop(1,"rgba(42,105,224,0)");context.beginPath();context.moveTo(points[0].x,pad.top+innerH);points.forEach(point=>context.lineTo(point.x,point.y));context.lineTo(points.at(-1)!.x,pad.top+innerH);context.closePath();context.fillStyle=gradient;context.fill();context.beginPath();points.forEach((point,index)=>index?context.lineTo(point.x,point.y):context.moveTo(point.x,point.y));context.strokeStyle="#2867dc";context.lineWidth=3;context.lineJoin="round";context.lineCap="round";context.stroke();points.forEach((point,index)=>{context.beginPath();context.arc(point.x,point.y,index===selected?5:3,0,Math.PI*2);context.fillStyle=index===selected?"#0f3f94":"#fff";context.fill();context.strokeStyle="#2867dc";context.lineWidth=2;context.stroke()})}context.textAlign="center";context.fillStyle="#7e8795";context.font="10px DM Sans, Arial";data.forEach((point,index)=>{if(width>560||index%2===0)context.fillText(point.label,points[index]?.x??0,height-10)})};draw();const observer=new ResizeObserver(draw);observer.observe(canvas);return()=>observer.disconnect()},[chartKey,peak,selected,data]);
  function selectPoint(event:React.MouseEvent<HTMLCanvasElement>){const rect=event.currentTarget.getBoundingClientRect(),index=Math.round(((event.clientX-rect.left-48)/Math.max(1,rect.width-66))*(data.length-1));setSelected(Math.max(0,Math.min(data.length-1,index)))}
  return <article className="traffic-chart-card"><header><div><span className="traffic-chart-icon">↗</span><div><h2>Website traffic</h2><p>Monthly visits and audience growth</p></div></div><div className="traffic-chart-period">Last 12 months</div></header><div className="traffic-chart-summary"><div><small>Total visits</small><strong>{total.toLocaleString()}</strong></div><div><small>This month</small><strong>{current.toLocaleString()}</strong></div><div><small>Monthly growth</small><strong className={growth<0?"down":""}>{growth>0?"+":""}{growth}%</strong></div><div><small>Unique visitors</small><strong>{(data.at(-1)?.visitors??0).toLocaleString()}</strong></div></div><div className="traffic-chart-canvas"><canvas ref={canvasRef} onMouseMove={selectPoint} onClick={selectPoint} aria-label="Monthly website visits chart"/>{selectedPoint&&<div className="traffic-chart-detail"><b>{selectedPoint.label}</b><span>{selectedPoint.visits} visits</span><span>{selectedPoint.visitors} visitors</span></div>}</div></article>;
}
